//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
// 
#pragma warning disable 1591

namespace SensePost.Wikto.com.sensepost.spud.obj {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStructResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::SensePost.Wikto.Properties.Settings.Default.wikto_com_sensepost_spud_obj_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStructResultCompletedEventHandler GetStructResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStructResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StructuredResult GetStructResult(string sz_q, int n_s, int n_l, bool b_g) {
            object[] results = this.Invoke("GetStructResult", new object[] {
                        sz_q,
                        n_s,
                        n_l,
                        b_g});
            return ((StructuredResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStructResult(string sz_q, int n_s, int n_l, bool b_g, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStructResult", new object[] {
                        sz_q,
                        n_s,
                        n_l,
                        b_g}, callback, asyncState);
        }
        
        /// <remarks/>
        public StructuredResult EndGetStructResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StructuredResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetStructResultAsync(string sz_q, int n_s, int n_l, bool b_g) {
            this.GetStructResultAsync(sz_q, n_s, n_l, b_g, null);
        }
        
        /// <remarks/>
        public void GetStructResultAsync(string sz_q, int n_s, int n_l, bool b_g, object userState) {
            if ((this.GetStructResultOperationCompleted == null)) {
                this.GetStructResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStructResultOperationCompleted);
            }
            this.InvokeAsync("GetStructResult", new object[] {
                        sz_q,
                        n_s,
                        n_l,
                        b_g}, this.GetStructResultOperationCompleted, userState);
        }
        
        private void OnGetStructResultOperationCompleted(object arg) {
            if ((this.GetStructResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStructResultCompleted(this, new GetStructResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StructuredResult {
        
        private int resultStartField;
        
        private int resultEndField;
        
        private int resultTotalField;
        
        private int resultGoogleTotalField;
        
        private int resultLiveTotalField;
        
        private int resultYahooTotalField;
        
        private string resultQueryStringField;
        
        private StructuredResultElement[] resultItemsField;
        
        /// <remarks/>
        public int ResultStart {
            get {
                return this.resultStartField;
            }
            set {
                this.resultStartField = value;
            }
        }
        
        /// <remarks/>
        public int ResultEnd {
            get {
                return this.resultEndField;
            }
            set {
                this.resultEndField = value;
            }
        }
        
        /// <remarks/>
        public int ResultTotal {
            get {
                return this.resultTotalField;
            }
            set {
                this.resultTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ResultGoogleTotal {
            get {
                return this.resultGoogleTotalField;
            }
            set {
                this.resultGoogleTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ResultLiveTotal {
            get {
                return this.resultLiveTotalField;
            }
            set {
                this.resultLiveTotalField = value;
            }
        }
        
        /// <remarks/>
        public int ResultYahooTotal {
            get {
                return this.resultYahooTotalField;
            }
            set {
                this.resultYahooTotalField = value;
            }
        }
        
        /// <remarks/>
        public string ResultQueryString {
            get {
                return this.resultQueryStringField;
            }
            set {
                this.resultQueryStringField = value;
            }
        }
        
        /// <remarks/>
        public StructuredResultElement[] ResultItems {
            get {
                return this.resultItemsField;
            }
            set {
                this.resultItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StructuredResultElement {
        
        private string resultSourceField;
        
        private string resultUrlField;
        
        private string resultCacheSizeField;
        
        private string resultSnippetField;
        
        private string resultSummaryField;
        
        private string resultTitleField;
        
        private string resultErrorCodeField;
        
        /// <remarks/>
        public string ResultSource {
            get {
                return this.resultSourceField;
            }
            set {
                this.resultSourceField = value;
            }
        }
        
        /// <remarks/>
        public string ResultUrl {
            get {
                return this.resultUrlField;
            }
            set {
                this.resultUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCacheSize {
            get {
                return this.resultCacheSizeField;
            }
            set {
                this.resultCacheSizeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultSnippet {
            get {
                return this.resultSnippetField;
            }
            set {
                this.resultSnippetField = value;
            }
        }
        
        /// <remarks/>
        public string ResultSummary {
            get {
                return this.resultSummaryField;
            }
            set {
                this.resultSummaryField = value;
            }
        }
        
        /// <remarks/>
        public string ResultTitle {
            get {
                return this.resultTitleField;
            }
            set {
                this.resultTitleField = value;
            }
        }
        
        /// <remarks/>
        public string ResultErrorCode {
            get {
                return this.resultErrorCodeField;
            }
            set {
                this.resultErrorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetStructResultCompletedEventHandler(object sender, GetStructResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStructResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStructResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StructuredResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StructuredResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591